<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: flib - Win32 (WCE x86) Release--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP580.tmp" with contents
[
/nologo /W3 /D _WIN32_WCE=300 /D "WIN32_PLATFORM_PSPC=310" /D "_i386_" /D UNDER_CE=300 /D "i_386_" /D "UNICODE" /D "_UNICODE" /D "_X86_" /D "x86" /D "NDEBUG" /Fp"X86Rel/redamation.pch" /Yu"stdafx.h" /Fo"X86Rel/" /Gs8192 /GF /Oxs /c 
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\animacion.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\entrada.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\flib.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\graph.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\main.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\mat.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\poli.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\stgapi.cpp"
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\trazo.cpp"
]
Creating command line "cl.exe @C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP580.tmp" 
Creating temporary file "C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP581.tmp" with contents
[
/nologo /W3 /D _WIN32_WCE=300 /D "WIN32_PLATFORM_PSPC=310" /D "_i386_" /D UNDER_CE=300 /D "i_386_" /D "UNICODE" /D "_UNICODE" /D "_X86_" /D "x86" /D "NDEBUG" /Fp"X86Rel/redamation.pch" /Yc"stdafx.h" /Fo"X86Rel/" /Gs8192 /GF /Oxs /c 
"C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\StdAfx.cpp"
]
Creating command line "cl.exe @C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP581.tmp" 
Creating temporary file "C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP582.tmp" with contents
[
commctrl.lib coredll.lib corelibc.lib aygshell.lib gx.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"WinMainCRTStartup" /incremental:no /pdb:"X86Rel/redamation.pdb" /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"X86Rel/redamation.exe" /subsystem:windowsce,3.00 /MACHINE:IX86 
".\X86Rel\animacion.obj"
".\X86Rel\dibujo.obj"
".\X86Rel\entrada.obj"
".\X86Rel\flib.obj"
".\X86Rel\graph.obj"
".\X86Rel\main.obj"
".\X86Rel\mat.obj"
".\X86Rel\poli.obj"
".\X86Rel\StdAfx.obj"
".\X86Rel\stgapi.obj"
".\X86Rel\trazo.obj"
]
Creating command line "link.exe @C:\DOCUME~1\pablo\LOCALS~1\Temp\RSP582.tmp"
<h3>Output Window</h3>
Compiling...
StdAfx.cpp
Compiling...
animacion.cpp
dibujo.cpp
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(269) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(269) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(288) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(288) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(294) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(294) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(317) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(317) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(334) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(334) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(336) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(336) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(338) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(338) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(340) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(340) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(342) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(342) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(376) : warning C4244: '+=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(376) : warning C4244: '+=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(392) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(393) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(415) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(415) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(509) : warning C4244: 'argument' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(509) : warning C4244: 'argument' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(551) : warning C4101: 'j' : unreferenced local variable
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(621) : warning C4101: 'j' : unreferenced local variable
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(721) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(721) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(724) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(725) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(726) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
C:\Documents and Settings\pablo\Desktop\srcpablo\redamation\dibujo.cpp(727) : warning C4244: '=' : conversion from 'long' to 'short', possible loss of data
entrada.cpp
flib.cpp
graph.cpp
main.cpp
mat.cpp
poli.cpp
stgapi.cpp
trazo.cpp
Generating Code...
Linking...



<h3>Results</h3>
redamation.exe - 0 error(s), 34 warning(s)
</pre>
</body>
</html>
